//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Champignons.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class str {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal str() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Champignons.Properties.str", typeof(str).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atention!.
        /// </summary>
        public static string Atent {
            get {
                return ResourceManager.GetString("Atent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You really want to leave?.
        /// </summary>
        public static string ConfLeave {
            get {
                return ResourceManager.GetString("ConfLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error to connect. The database connection didn&apos;t work!.
        /// </summary>
        public static string ConnError {
            get {
                return ResourceManager.GetString("ConnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave.
        /// </summary>
        public static string Leave {
            get {
                return ResourceManager.GetString("Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong username or password!.
        /// </summary>
        public static string LogError {
            get {
                return ResourceManager.GetString("LogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level One.
        /// </summary>
        public static string Lvl1 {
            get {
                return ResourceManager.GetString("Lvl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Ten.
        /// </summary>
        public static string Lvl10 {
            get {
                return ResourceManager.GetString("Lvl10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Two.
        /// </summary>
        public static string Lvl2 {
            get {
                return ResourceManager.GetString("Lvl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 2+1=TREE.
        /// </summary>
        public static string Lvl3 {
            get {
                return ResourceManager.GetString("Lvl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Four.
        /// </summary>
        public static string Lvl4 {
            get {
                return ResourceManager.GetString("Lvl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Five.
        /// </summary>
        public static string Lvl5 {
            get {
                return ResourceManager.GetString("Lvl5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Six.
        /// </summary>
        public static string Lvl6 {
            get {
                return ResourceManager.GetString("Lvl6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Seven.
        /// </summary>
        public static string Lvl7 {
            get {
                return ResourceManager.GetString("Lvl7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Eight.
        /// </summary>
        public static string Lvl8 {
            get {
                return ResourceManager.GetString("Lvl8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Nine.
        /// </summary>
        public static string Lvl9 {
            get {
                return ResourceManager.GetString("Lvl9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Zero.
        /// </summary>
        public static string LvlEnd {
            get {
                return ResourceManager.GetString("LvlEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must type your password!.
        /// </summary>
        public static string PassError {
            get {
                return ResourceManager.GetString("PassError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave?.
        /// </summary>
        public static string QuestLeave {
            get {
                return ResourceManager.GetString("QuestLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champignons © 2018 ALL RIGHTS RESERVERD.
        /// </summary>
        public static string Rights {
            get {
                return ResourceManager.GetString("Rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must type your username!.
        /// </summary>
        public static string UserError {
            get {
                return ResourceManager.GetString("UserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome, .
        /// </summary>
        public static string Wel1 {
            get {
                return ResourceManager.GetString("Wel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I think you can go now..
        /// </summary>
        public static string Wel10 {
            get {
                return ResourceManager.GetString("Wel10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finally, fuck me!.
        /// </summary>
        public static string Wel11 {
            get {
                return ResourceManager.GetString("Wel11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finally, fuck you!!!.
        /// </summary>
        public static string Wel12 {
            get {
                return ResourceManager.GetString("Wel12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OH MY GOWD, FUCK YOU PIECE OF SHIT, GO AWAY OF HERE!.
        /// </summary>
        public static string Wel13 {
            get {
                return ResourceManager.GetString("Wel13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s your birthday and that&apos;s beautifull!.
        /// </summary>
        public static string Wel2 {
            get {
                return ResourceManager.GetString("Wel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here, I preper a little game for you, the only thing you need to do is win the game..
        /// </summary>
        public static string Wel3 {
            get {
                return ResourceManager.GetString("Wel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you reach the end, you will receive something, but you, and I, don&apos;t know what..
        /// </summary>
        public static string Wel4 {
            get {
                return ResourceManager.GetString("Wel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you don&apos;t, go fuck yourself, ok?.
        /// </summary>
        public static string Wel5 {
            get {
                return ResourceManager.GetString("Wel5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you ready to go?.
        /// </summary>
        public static string Wel6 {
            get {
                return ResourceManager.GetString("Wel6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, it&apos;s loading....
        /// </summary>
        public static string Wel7 {
            get {
                return ResourceManager.GetString("Wel7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ohh, fuck, I almost forgot..
        /// </summary>
        public static string Wel8 {
            get {
                return ResourceManager.GetString("Wel8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For each &apos;level&apos; you&apos;ll have a tip, but it&apos;s only appers if you click on the button in the screen..
        /// </summary>
        public static string Wel9 {
            get {
                return ResourceManager.GetString("Wel9", resourceCulture);
            }
        }
    }
}
